const SERVER_PORT = process.env.SERVER_PORT || 8080;

const SONDAS_CANTIDAD = process.env.SONDAS_CANTIDAD || 5;
const TEMPERATURA_MIN = process.env.TEMPERATURA_MIN || -20;
const TEMPERATURA_MAX = process.env.TEMPERATURA_MAX || 100;

const SONDAS_CONFIG = {
  SONDAS_CANTIDAD,
};

const TEMPERATURA_CONFIG = {
  TEMPERATURA_MIN,
  TEMPERATURA_MAX,
};

export { SERVER_PORT, SONDAS_CONFIG, TEMPERATURA_CONFIG };
